Burger/Models/Meal.cs
namespace Burger.Models
{
    public class Meal
    {
        public int Id { get; set; }
        [MaxLength(255), MinLength(2, ErrorMessage = "At Least 2 Chars")]
        public string Name { get; set; }

        [MaxLength(500), MinLength(2, ErrorMessage = "At Least 2 Chars")]
        public string Description { get; set; }

        public double Price { get; set; }

        public string Image { get; set; }

        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }
    }

}

Burger/Areas/Admin/Controllers/MealsController.cs
namespace Burger.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]

    [Area("Admin")]
    //[Authorize(Roles = "Admin")]
    public class MealsController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IMealService _mealService;

        public MealsController(ICategoryService categoryService,IMealService mealService)
        {
            this._categoryService = categoryService;
            this._mealService = mealService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _mealService.MealsWithItsCategory());
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Categories =new SelectList( await _categoryService.GetAll(),"Id","Name");
            
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(MealVM model)
        {


            if (ModelState.IsValid)
            {
                string ImagePath = await _mealService.GameCoverPath(model.Image);
                var meal = new Meal
                {
                    Name = model.Name,
                    CategoryId = model.CategoryId,
                    Description = model.Description,
                    Price = model.Price,
                    Image=ImagePath
                    
                };
                await _mealService.Insert(meal);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Categories = new SelectList(await _categoryService.GetAll(), "Id", "Name");

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.Categories = new SelectList(await _categoryService.GetAll(), "Id", "Name");

            Meal meal =await _mealService.GetById(id);
            if (meal == null) return RedirectToAction(nameof(Index));
            TempData["ID"] = meal.Id;

            MealVM model = new MealVM();
            if (meal != null)
            {

                 model = new MealVM
                {
                    Name = meal.Name,
                    CategoryId = meal.CategoryId,
                    Description = meal.Description,
                    Price = meal.Price,
                };
                TempData["Image"] = meal.Image;
                ViewBag.Image=meal.Image;

            }

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(MealVM model, int? id)
        {


            if (ModelState.IsValid)
            {
                var meal = new Meal
                {
                    Id=(int)id,
                    Name = model.Name,
                    CategoryId = model.CategoryId,
                    Description = model.Description,
                    Price = model.Price,
                    
                };
                if (model.Image!=null)
                {
                    string ImagePath = await _mealService.GameCoverPath(model.Image);
                    meal.Image = ImagePath;
                }
                else
                {
                    var Image = TempData["Image"] as string;
                    meal.Image = Image;
                }


                    await _mealService.Update(meal);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Categories = new SelectList(await _categoryService.GetAll(), "Id", "Name");

            return View();
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _mealService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Burger/Areas/Admin/Views/Meals/Create.cshtml
@model MealVM

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row">
        <div class="col-md-8">
            <div class="form-group mb-2">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group mb-2">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group mb-2">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-items="ViewBag.Categories" asp-for="CategoryId" class="form-control"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>

            

            <div class="form-group mb-2">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group mb-2">
                <label asp-for="Image" class="control-label"></label>
                <input type="file" asp-for="Image"accept=".png,.jpg,.jpeg" class="form-control" id="fileInput" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-success form-control" />
            </div>
        </div>
        <div class="col-md-4 d-block d-flex justify-content-center space-between-center" id="coverSection">
            <img src="" id="coverImage" alt="Cover Image" style="width: 100%;  display: none;" />
        </div>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script>
            document.getElementById('fileInput').addEventListener('change', function (event) {
                const file = event.target.files[0]; // Get the selected file
                const imgElement = document.getElementById('coverImage');

                if (file && file.type.startsWith('image/')) {
                    const reader = new FileReader(); // Create a FileReader to read the file

                    reader.onload = function (e) {
                        imgElement.src = e.target.result; // Set the image source to the file's data URL
                        imgElement.style.display = 'block'; // Show the image
                    };

                    reader.readAsDataURL(file); // Read the file as a data URL
                } else {
                    imgElement.src = ''; // Clear the image source if no valid file is selected
                    imgElement.style.display = 'none'; // Hide the image
                }
            });
        </script>
    }
}

Burger/Areas/Admin/Views/Meals/Edit.cshtml
@model MealVM

@{
    ViewData["Title"] = "Edit";
}

<h2>Update</h2>

<form asp-action="Edit" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row">
        <input id="ID" name="ID" class="form-control mb-3" value="@TempData["ID"]" hidden />

        <div class="col-md-8">

            <div class="form-group mb-2">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group mb-2">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group mb-2">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-items="ViewBag.Categories" asp-for="CategoryId" class="form-control"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>



            <div class="form-group mb-2">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group mb-2">
                <label asp-for="Image" class="control-label"></label>
                <input type="file" asp-for="Image" value="@ViewBag.Image" accept=".png,.jpg,.jpeg" class="form-control" id="fileInput" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-success form-control" />
            </div>
        </div>
        @if (string.IsNullOrEmpty(@ViewBag.Image))
        {
            <div class="col-md-4 d-block d-flex justify-content-center space-between-center" id="coverSection">
                <img src="" id="coverImage" alt="Cover Image" style="width: 100%;  display: none;" />
            </div>
        }
        else{
            <div class="col-md-4 d-block d-flex justify-content-center space-between-center" id="coverSection">
                <img src="~/assets/Images//Meals/@ViewBag.Image"  id="coverImage" alt="Cover Image" style="width: 100%" />
            </div>
        }
        
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script>
            document.getElementById('fileInput').addEventListener('change', function (event) {
                const file = event.target.files[0]; // Get the selected file
                const imgElement = document.getElementById('coverImage');

                if (file && file.type.startsWith('image/')) {
                    const reader = new FileReader(); // Create a FileReader to read the file

                    reader.onload = function (e) {
                        imgElement.src = e.target.result; // Set the image source to the file's data URL
                        imgElement.style.display = 'block'; // Show the image
                    };

                    reader.readAsDataURL(file); // Read the file as a data URL
                } else {
                    imgElement.src = ''; // Clear the image source if no valid file is selected
                    imgElement.style.display = 'none'; // Hide the image
                }
            });
        </script>
    }
}

Burger/Areas/Admin/Views/Meals/Index.cshtml
@model ICollection<Meal> 
@{

    ViewData["Title"] = "Meals Page";

    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<a class="btn btn-outline-success form-control" asp-action="Create" asp-controller="Meals" asp-area="Admin">Add New Meal</a>

<div class="report-container">
    <div class="report-header">
        <h1 class="recent-Articles">Meals</h1>
    </div>

    <div class="report-body">
        <table class="table table-bordered text-center ">
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Category</th>
                <th>Image</th>
                <th></th>
                <th></th>
            </tr>
            <tbody >

           
                @foreach (var meal in Model)
            {
                    <tr>
                    <td>@meal.Name</td>
                    <td>@meal.Description</td>
                    <td>@meal.Price</td>
                    <td>@meal.Category.Name</td>
                    <td>
                        <img src="@Utilites.ImagePath@meal.Image" class="w-50" alt="@meal.Image" />
                    </td>
                        <td><a asp-action="Edit" asp-controller="Meals" 
                            asp-area="Admin" class="btn btn-outline-info"
                            asp-route-id="@meal.Id">Update</a>
                        </td>
                    <td>
                        <a asp-action="Delete" asp-controller="Meals"
                               asp-area="Admin" class="btn btn-outline-danger"
                        asp-route-id="@meal.Id">Delete</a>
                    </td>
                </tr>
            }

            </tbody>
        </table>

    </div>



</div>